id: P73DA045B
initial_creation_type: ocr
source_metadata:
  volumes:
    3a7a13a3715a47d9ba6fe146835d6e52:
      base_file: v005.txt
      image_group_id: I1PD95850
      title: གཏོར་མའི་ཆོ་ག།
      total_pages: 2069
      volume_number: 5
